arch

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -10,7 +10,7 @@ export GPG_TTY=$(tty)
 
 # ZSH Setup
 ZSH_THEME="refined"
-plugins=(cp fast-syntax-highlighting fzf git ubuntu zsh-autosuggestions)
+plugins=(archlinux cp fast-syntax-highlighting fzf git zsh-autosuggestions)
 source $ZSH/oh-my-zsh.sh
 
 # Aliases
@@ -22,14 +22,15 @@ alias as="apt search"
 alias cp="cpv"
 alias rm="trash"
 alias c="clear"
-alias fzf="fzf --style full"
+alias fzf="fzf --preview 'bat --style=numbers --color=always {}'"
 alias dir="cd ~ && cd \$(find * -type d | fzf)"
 alias ff="fastfetch 2>/dev/null"
 alias vim="zed"
+alias yayf="yay -Slq | fzf --multi --preview 'yay -Sii {1}' --preview-window=down:75% | xargs -ro yay -S"
 
 # Evals
 eval "$(zoxide init zsh)"
-eval "$(~/.local/bin/mise activate zsh)"
+eval "$(mise activate zsh)"
 
 # FZF Plugin Config
 export FZF_CTRL_T_OPTS="
@@ -58,3 +59,53 @@ else
 fi
 unset __conda_setup
 # <<< conda initialize <<<
+
+web2app() {
+  if [ "$#" -ne 3 ]; then
+    echo "Usage: web2app <AppName> <AppURL> <IconURL> (IconURL must be in PNG -- use https://dashboardicons.com)"
+    return 1
+  fi
+
+  local APP_NAME="$1"
+  local APP_URL="$2"
+  local ICON_URL="$3"
+  local ICON_DIR="$HOME/.local/share/applications/icons"
+  local DESKTOP_FILE="$HOME/.local/share/applications/${APP_NAME}.desktop"
+  local ICON_PATH="${ICON_DIR}/${APP_NAME}.png"
+
+  mkdir -p "$ICON_DIR"
+
+  if ! curl -sL -o "$ICON_PATH" "$ICON_URL"; then
+    echo "Error: Failed to download icon."
+    return 1
+  fi
+
+  cat > "$DESKTOP_FILE" <<EOF
+[Desktop Entry]
+Version=1.0
+Name=$APP_NAME
+Comment=$APP_NAME
+Exec=chromium --new-window --ozone-platform=wayland --app="$APP_URL" --name="$APP_NAME" --class="$APP_NAME"
+Terminal=false
+Type=Application
+Icon=$ICON_PATH
+StartupNotify=true
+EOF
+
+  chmod +x "$DESKTOP_FILE"
+}
+
+web2app-remove() {
+  if [ "$#" -ne 1 ]; then
+    echo "Usage: web2app-remove <AppName>"
+    return 1
+  fi
+
+  local APP_NAME="$1"
+  local ICON_DIR="$HOME/.local/share/applications/icons"
+  local DESKTOP_FILE="$HOME/.local/share/applications/${APP_NAME}.desktop"
+  local ICON_PATH="${ICON_DIR}/${APP_NAME}.png"
+
+  rm "$DESKTOP_FILE"
+  rm "$ICON_PATH"
+}
